### ISSUE TITLE
capexec: CAP_SYS_OPERATIONS is not supported on this system

### ISSUE THREAD

**Issue by ilnuribat** [blackav/regionals-2015-training#1]
https://ejudge.ru/forum/viewtopic.php?f=5&t=1874
У нас такая же проблема, но переустанавливать нет желания)

**Comment by blackav** [comment]
https://ejudge.ru/forum/viewtopic.php?f=5&t=1973

**Comment by ilnuribat** [comment]
Спасибо, помогло)

Правда, мы сперва не сделал Reset contest, поэтому не сразу сработало.
